# encoding: utf-8

################################
# Rake configuration
################################

# Paths
BUILD_DIR = File.join('.build').freeze
RELEASES_ROOT_DIR = File.join('releases').freeze
PROJECT_NAME = 'Configurator'.freeze

desc 'Build Configurator'
task :build, [:configuration, :arch, :sdks, :is_archive] do |task, args|
  # Set task defaults
  args.with_defaults(:configuration => 'debug', :sdks => ['IPhone 11'])

  unless args.configuration == 'Debug'.downcase || args.configuration == 'Release'.downcase
    fail("Unsupported configuration. Valid values: ['debug', 'release']. Found '#{args.configuration}''")
  end

  # Clean data generated by spm
  system("rm -rf #{BUILD_DIR} > /dev/null 2>&1")

  # Build
  build_paths = []
  args.sdks.each do |sdk|
    spm_build(args.configuration, args.arch)
    # path of the package looks like: `.build/(debug|release)/Configurator`
    build_path = File.join(BUILD_DIR, args.configuration, PROJECT_NAME)
    build_paths.push(build_path)
  end

  puts(build_paths)

  if args.configuration == 'Release'.downcase and args.is_archive
    puts "Creating release zip"
    create_release_zip(build_paths)
  end
end

desc 'Run tests with SPM'
task :test do
  spm_test
end

desc 'Create a release zip'
task :archive do
  Rake::Task["build"].invoke('release', ['macos'], 'true')
end

desc 'Generates a Swift class with the file content from Resources'
task :gen_resources do
  gen_fake_resources
end

################################
# Helper functions
################################

def spm_build(configuration, arch)
  spm_cmd = "swift build "\
            "-c #{configuration} "\
            "#{arch.nil? ? "" : "--triple #{arch}"} "\
            "--disable-sandbox"
  p spm_cmd
  system(spm_cmd) or abort "Build failure"
end

def spm_test()
  spm_cmd = "swift test"
  system(spm_cmd) or abort "Test failure"
end

def create_release_zip(build_paths)
  release_dir = RELEASES_ROOT_DIR

  # Create and move files into the release directory
  mkdir_p release_dir
  cp_r build_paths[0], release_dir

  # Get the current version from the Swift Version file
  version = get_version
  unless version
    fail("Version not found")
  end

  output_artifact_basename = "#{PROJECT_NAME}-#{version}.zip"

  Dir.chdir(release_dir) do
    # -X: no extras (uid, gid, file times, ...)
    # -r: recursive
    system("zip -X -r #{output_artifact_basename} .") or abort "zip failure"
    # List contents of zip file
    system("unzip -l #{output_artifact_basename}") or abort "unzip failure"
  end
end

def get_version
  version_file = File.open('Sources/Version.swift').read
  /let current = \"(?<version>.*)\"/ =~ version_file
  version
end